MVCAutoShop/AutoshopMVC/Controllers/AppointmentController.cs
using System;
using System.Collections.Generic;
using System.Composition;
using System.Linq;
using System.Security.Claims;
using System.Text;
using System.Threading.Tasks;
using AutoshopMVC.Models;
using BAL.Interfaces;
using BAL.Models;
using BAL.Services;
using BAL.Utilities;
using DAL.Entities;
using javax.jws;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;

namespace AutoshopMVC.Controllers
{

    public class AppointmentController : Controller
    {
        private IAppointmentService appointmentService;
        private UserManager<User> _userManager;
        BigAppointmentModel model;

        public AppointmentController(UserManager<User> userManager)
        {
            appointmentService = new AppointmentService();
            _userManager = userManager;
            model = new BigAppointmentModel();
        }

        [Authorize]
        public IActionResult Index()
        {
            return View(model);
        }
        
        [Authorize]
        [HttpPost]
        public IActionResult MakeAppointment(BigAppointmentModel bigAppointment)
        {
            bigAppointment.appointmentModel.CreationUser = _userManager.GetUserAsync(User).Id;
            appointmentService.MakeNewAppointment(bigAppointment.appointmentModel);
            
            return View("Index");
        }

        [Authorize]
        [HttpGet]
        public IActionResult RefreshAppointments(BigAppointmentModel model)
        {
            model.appointmentsPerDay =  appointmentService.GenerateReports(model.startDate.Date, model.startDate.Date.AddDays(1));
            return View("Index", model);
        }

        [Authorize]
        public IActionResult FinalizeAppointment(int id)
        {
                AppointmentModel appointment = appointmentService.GetAppointment(id);
                appointmentService.FinishAppointment(appointment);
                return View("Index", model);
        }

        [Authorize]
        [HttpGet]
        public IActionResult GenerateReports(BigAppointmentModel model)
        {
            model.generatedAppointmentReports = appointmentService.GenerateReports(model.startDate.Date, model.endDate.Date.AddDays(1));
            TempData["generatedReport"] = JsonConvert.SerializeObject(model.generatedAppointmentReports);
            return View("Index", model);
        }

        [Authorize]
        [Route("Export")]
        public IActionResult Export(String exporterParam)
        {
            ExporterFactory factory = new ExporterFactory();
            Exporter exporter = factory.CreateExporter(exporterParam);
            IEnumerable<AppointmentModel> report = JsonConvert.DeserializeObject<IEnumerable<AppointmentModel>>(TempData["generatedReport"].ToString()); ;
            String data = exporter.ExportFile(report);
            TempData.Keep();
            return File(Encoding.ASCII.GetBytes(data), "application/json", "report.txt");
        }
    }
}

MVCAutoShop/AutoshopMVC/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using AutoshopMVC.Models;

namespace AutoshopMVC.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult About()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

MVCAutoShop/AutoshopMVC/Views/Home/About.cshtml
@{
    ViewData["Title"] = "About";
}

<h1>About</h1>

MVCAutoShop/AutoshopMVC/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

@using Microsoft.AspNetCore.Identity
@using DAL.Entities
@inject SignInManager<User> SignInManager
@inject UserManager<User> UserManager

<div class="row">
    <div class="col-12 p-0">
        <div class="jumbotron min-vh-100 text-center m-0  d-flex flex-column justify-content-center">
            @if (SignInManager.IsSignedIn(User))
            {
                <h1 class="display-4">Welcome back!</h1>
                <p class="lead">
                    <a class="btn btn-success btn-lg" asp-area="" asp-controller="Appointment" asp-action="Index" role="button">Manage Appointments</a>
                </p>
            }
            else
            {
                <h1 class="display-4">Welcome, guest</h1>
                <p class="lead">Join us on our journey.</p>
                <p class="lead">
                    <a class="btn btn-success btn-lg" asp-area="Identity" asp-page="/Account/Login" role="button">Login</a>
                    <a class="btn btn-success btn-lg" asp-area="Identity" asp-page="/Account/Register" role="button">Register</a>
                </p>
            }
        </div>
    </div>
</div>